#pragma once
#include "calculator/operations/addition_operation.hpp"
#include "calculator/calculator.hpp"
#include "console_runner_calculator.hpp"
#include "calculator/operations/division_operation.hpp"
#include "calculator/operations/multiplication_operation.hpp"
#include "calculator/operation.hpp"
#include "calculator/operations/pow_operation.hpp"
#include "calculator/operations/subtraction_operation.hpp"
